version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app 
    command: sh -c "cd nextjs-blog && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"